In [1]:
import pandas as pd

In [2]:
filename = "/home/shared_data/Bmaps/Mu2e_DSMap_V13.p"

In [3]:
df = pd.read_pickle(filename)

In [4]:
df

,X,Y,Z,Bx,By,Bz,R,Phi,Bphi,Br
0,-1.2,-1.2,3.071,1284.125788,1307.100001,442.195248,1.697056,-2.356194,-16.245222,-1832.273327
1,-1.2,-1.2,3.096,1312.127380,1335.143291,410.874370,1.697056,-2.356194,-16.274707,-1871.903043
2,-1.2,-1.2,3.121,1339.646202,1362.701661,376.958648,1.697056,-2.356194,-16.302671,-1910.848499
3,-1.2,-1.2,3.146,1366.531533,1389.624290,340.379319,1.697056,-2.356194,-16.329045,-1948.896473
4,-1.2,-1.2,3.171,1392.610688,1415.737061,301.071838,1.697056,-2.356194,-16.352815,-1985.801737
...,...,...,...,...,...,...,...,...,...,...
4902084,1.2,1.2,15.971,205.452081,204.896327,362.118995,1.697056,0.785398,-0.392978,290.160142
4902085,1.2,1.2,15.996,200.959435,200.443981,358.156213,1.697056,0.785398,-0.364481,283.835077
4902086,1.2,1.2,16.021,196.581608,196.105341,354.221831,1.697056,0.785398,-0.336772,277.671604
4902087,1.2,1.2,16.046,192.315417,191.877252,350.317143,1.697056,0.785398,-0.309830,271.665242
4902088,1.2,1.2,16.071,188.157767,187.756646,346.443323,1.697056,0.785398,-0.283635,265.811630

In [5]:
100*100*8

80000